# Generated by Django 2.2.8 on 2020-02-19 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200219_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commented',
            field=models.ManyToManyField(blank=True, related_name='commented', to=settings.AUTH_USER_MODEL),
        ),
    ]
